### PR TITLE
update to the latest version of autogluon

### PR DESCRIPTION
**Pull request by yoheigon**
Issue #, if available:
#1208
Description of changes:
Updated autogluon version to the latest and changed some methods for inference.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yijiezh** [comment]
Hi @yoheigon, I don't think the unity notebook is in a good shape for public yet. And it should be in a separate PR to review more properly.

**Comment by yoheigon** [comment]
> Hi @yoheigon, I don't think the unity notebook is in a good shape for public yet. And it should be in a separate PR to review more properly.

This is for AutoGluon, not for Unity

**Comment by yijiezh** [comment]
> > Hi @yoheigon, I don't think the unity notebook is in a good shape for public yet. And it should be in a separate PR to review more properly.
> 
> This is for AutoGluon, not for Unity

Yes, I think unity notebook change is somehow included in the pr.

**Comment by yoheigon** [comment]
> > > Hi @yoheigon, I don't think the unity notebook is in a good shape for public yet. And it should be in a separate PR to review more properly.
> > 
> > 
> > This is for AutoGluon, not for Unity
> 
> Yes, I think unity notebook change is somehow included in the pr.

Yup, change a branch

**Pull request closed without merging**
