### PR TITLE
Fixed issue with setup.sh script

### PR DESCRIPTION
**Pull request by mattmcclean**
Previously running this script on a non-SageMaker notebook instance would give an error "Error: argument "agent" is wrong: table id value is invalid". Moved the variables inside the RUNNING_ON_NOTEBOOK_INSTANCE if statement to make sure it works outside SageMaker notebook instance

### CODE REVIEW

**Comment by winstonaws** [comment]
Hey Matt, this script should only be needed on SageMaker notebook instances. It's also temporary and we're working to get rid of it, so I'd prefer not to make changes to it.

Is there a reason you need to run it outside of SageMaker notebooks? You should be able to use local mode without it, as long as you have docker and docker-compose installed.

**Comment by winstonaws** [comment]
I'm going to close this PR given the above, but please reopen if you feel it's still needed and want to continue talking about it.

**Comment by mattmcclean** [comment]
One reason for running outside of a SageMaker notebook is the limited disk space available for Docker images. Had to spin up an EC2 instance with the Deep Learning AMI instead.

**Comment by winstonaws** [comment]
Right, what I mean is that you shouldn't need the setup.sh script when using local mode outside of SageMaker notebook instances. Did you have issues without the script?

**Pull request closed without merging**
