### PR TITLE
Highly performant TensorFlow batch inference and training example

### PR DESCRIPTION
**Pull request by rabowskyb**
*Description of changes:  this PR adds an example notebook and related code for doing highly performant TensorFlow batch inference and training (with Horovod).  This example will be used in an upcoming AWS ML Blog post.  

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by andremoeller** [comment]
Run and reviewed -- good to merge in!

**Comment by rabowskyb** [comment]
Does this belong in the sagemaker_batch_transform directory?  also, should the tf container versions be updated to tf 1.13 (currently on tf 1.12)?

**Comment by j3ffreyjohn** [comment]
Yes, all notebooks showcasing batch transform should live in the top-level sagemaker_batch_transform directory.

**Comment by rabowskyb** [comment]
I've moved the example to the batch transform directory and updated to tf 1.13; please review and merge.  Thanks!

**Pull request merged**
