### PR TITLE
Add autopilot customer churn notebook

### PR DESCRIPTION
**Pull request by juliodelgadoaws**
Similar to the XGBoost customer churn notebook, but using autopilot
instead.

*Issue #, if available:*

*Description of changes:*

To support Aurora ML blog (https://aws.amazon.com/blogs/aws/new-for-amazon-aurora-use-machine-learning-directly-from-your-databases/) it is necessary to have a Customer Churn Autopilot example. 

The blog currently references: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/xgboost_customer_churn/xgboost_customer_churn.ipynb but the resulting endpoint from this notebook is not usable from Aurora, since it does not include all the pre/post processing code generated.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pdasamzn** [comment]
I would restrict the MaxCandidates to be less that 20 with explicit instruction on how to increase. https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_AutoMLJobCompletionCriteria.html#sagemaker-Type-AutoMLJobCompletionCriteria-MaxCandidates

This would imply that we may not have 96% accuracy as mentioned in the later section of the doc.

**Comment by juliodelgadoaws** [comment]
> You can specify that the 'Churn?' contains 2 values & hence it's a binary classification problem. However, we don't need to specify as Autopilot will be able to infer it.

Make sense.

**Comment by juliodelgadoaws** [comment]
> I would restrict the MaxCandidates to be less that 20 with explicit instruction on how to increase. https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_AutoMLJobCompletionCriteria.html#sagemaker-Type-AutoMLJobCompletionCriteria-MaxCandidates
> 
> This would imply that we may not have 96% accuracy as mentioned in the later section of the doc.

Will modify and run a couple of times to make sure I have a correct ballpack value in the text for the accuracy.

**Comment by pdasamzn** [comment]
lgtm!

**Pull request merged**
